# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'

# UI库
def ui
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'MJRefresh'
  pod 'Toast-Swift'
end

# 工具库
def tool
  pod 'Alamofire'
  pod 'TXIMSDK_Plus_iOS', '~> 5.7.1435'
  pod 'TXCopyrightedMedia', '1.0.3'
end

def pod_local(type)
  pod "TXLiteAVSDK_#{type}"
  pod "TUICore", :path => "../TUICore"
  pod "TUIBeauty", :path => "../TUIBeauty"
  loadLocalTUIComponent('TUIPusher', type)
  loadLocalTUIComponent('TUIPlayer', type)
  
  loadLocalTUIWidgetWithSubspec('TUIAudioEffect', type)
  loadLocalTUIWidget('TUIBarrage')
  loadLocalTUIWidget('TUIGift')
  
end

def loadLocalTUIComponent(name, type)
  pod "#{name}/#{type}", :path => "../#{name}/"
end

def loadLocalTUIWidget(name)
  pod "#{name}", :path => "../#{name}/"
end

def loadLocalTUIWidgetWithSubspec(name, type)
  pod "#{name}/#{type}", :path => "../#{name}/"
end

target 'XiaoZhiBoApp' do
  use_frameworks!
  ui
  tool
  pod_local('Live')
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
